# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts "Start"

Challenge.destroy_all
Bookmarked.destroy_all
RoleModel.destroy_all
Participation.destroy_all
User.destroy_all

user = User.create(email:"a@a.com", password: "challenge", username: "aha")
user2 = User.create(email:"yo@yo.com", password: "challenge", username: "yoyo")
user3 = User.create(email:'leprince.antoine7@gmail.com', password: "123456", username: "antoinelp")
user4 = User.create(email:'demo@gmail.com', password: "challenge", username: "eugenie")



mascotte = RoleModel.create(first_name:"Super", last_name: "Challenger", gender:"Other", sector:"Entertainment", description: "I am here to motivate you and help you grow into the best version of yourself!", picture: "dragon_model.png")

elon = RoleModel.create(first_name: "Elon", last_name: "Musk", gender:"Male", sector: "Tech,Entrepreneurship", description: "Entrepreneur and businessman who founded X.com in 1999 (which later became PayPal), SpaceX in 2002 and Tesla Motors in 2003. Musk became a multimillionaire in his late 20s when he sold his start-up company, Zip2, to a division of Compaq Computers.", picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Elon_Musk_Royal_Society.jpg/260px-Elon_Musk_Royal_Society.jpg")
riri = RoleModel.create(first_name: "Rihanna", last_name: "Fenty", sector: "Entrepreneurship,Entertainment", gender: "Female", description: "Famour singer, entrepreneur, business woman", picture: "https://www.themartinicanwayoflife.com/wp-content/uploads/2016/04/o-RIHANNA-900.jpg")
sofia = RoleModel.create(first_name: "Sofia", last_name: "Kovalevskaya", sector: "Mathematics", gender: "Female", description: "She was the first woman in modern Europe to gain a doctorate in mathematics, the first to join the editorial board of a scientific journal, and the first to be appointed professor of mathematics.", picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Sofja_Wassiljewna_Kowalewskaja_1.jpg/220px-Sofja_Wassiljewna_Kowalewskaja_1.jpg")
ada = RoleModel.create(first_name: "Ada", last_name: "Lovelace", sector: "Mathematics,Programming", gender: "Female", description: "has been called the world's first computer programmer. What she did was write the world's first machine algorithm for an early computing machine that existed only on paper.", picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Ada_Lovelace_Chalon_portrait.jpg/600px-Ada_Lovelace_Chalon_portrait.jpg")
dorca = RoleModel.create(first_name: "Dorcas", last_name: "Muthoni", sector: "Entrepreneurship", gender: "Female", description: "She is founder and Chief Executive Officer of Openworld Ltd, a specialist computer software company she established in Kenya when she was just 24 years old. Today, Openworld is a leading e-Government and business software services firm involved in the delivery of some of the most widely used Web and Cloud applications in Africa, such as ARIS, an African Union reporting application used by all 54 member states; and the Performance Management System for the Government of Kenya, automating performance contracting in the public sector.", picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Dorcasquadrehonoris.jpg/220px-Dorcasquadrehonoris.jpg")
serena = RoleModel.create(first_name: "Serena", last_name: "Williams", sector: "Sports", gender: "Female", description: "She is an American tennis player who revolutionized women’s tennis with her powerful style of play and who won more Grand Slam singles titles than any other woman or man during the open era.", picture: "https://cdn.cnn.com/cnnnext/dam/assets/181002121444-serena-williams-file-exlarge-169.jpg")
sheryl = RoleModel.create(first_name: "Sheryl", last_name: "Sandberg", sector: "Business", gender: "Female", description: "She is a high-profile woman in the tech world. She is the chief operating officer (COO) of Facebook and founder of Leanin.org. In June 2012, she was elected to Facebook's board of directors by the existing board members, becoming the first woman to serve on its board.", picture: "https://fortunedotcom.files.wordpress.com/2017/09/06-sandberg-crop.jpg?w=840&h=485&crop=1")
ines = RoleModel.create(first_name: "Inès", last_name: "Leonarduzzi", sector: "Entrepreneur,Tech,Environment", gender: "Female", description: "She is a digital entrepreneur. In 2017, she launched her own company dedicated to 'digital ecolody'.", picture: "https://www2.businessofeminin.com/wp-content/uploads/2018/09/ines-leonarduzzi-featured-600x471.jpg")
emma = RoleModel.create(first_name: "Emma", last_name: "Watson", sector: "Entertainment", gender: "Female", description: "Famous actress, model and advocate for gender equality. She is notably an ambassador of the global HeForShe movement launched by the UN Women in 2014", picture: "https://cache.net-a-porter.com/content/images/story-body-content-V1-0-1537350316166.jpeg/w1900_q65.jpeg")
aragorn = RoleModel.create(first_name:"Aragorn", last_name: "Son of Arathorn", gender:"Male", sector:"Fictional", description: "Aragorn II, son of Arathorn is a fictional character from J. R. R. Tolkien's legendarium. He is one of the main protagonists of The Lord of the Rings. Aragorn was a Ranger of the North, first introduced with the name Strider at Bree, as the Hobbits continued to call him throughout The Lord of the Rings. He was eventually revealed to be the heir of Isildur and rightful claimant to the thrones of Arnor and Gondor. He was also a confidant of Gandalf and an integral part of the quest to destroy the One Ring and defeat the Dark Lord Sauron.
Aragorn led the Fellowship of the Ring following the loss of Gandalf in the Mines of Moria while fighting the Balrog. When the Fellowship was broken, he tracked the hobbits Meriadoc Brandybuck and Peregrin Took with the help of Legolas the elf and Gimli the dwarf to Fangorn Forest. He then fought in the battle at Helm's Deep and the Battle of the Pelennor Fields. After defeating Sauron's forces in Gondor, he led an army of Gondor and Rohan against the Black Gate of Mordor to distract Sauron's attention so that Frodo Baggins and Samwise Gamgee could have a chance to destroy the One Ring.
At the end of The Lord of the Rings, Aragorn was crowned King Elessar Telcontar ('Elfstone Strider') of Gondor. He married Elrond's daughter, Arwen, and assumed the Sceptre of Annúminas as King of Arnor, uniting the two kingdoms for the first time since the reign of Isildur.", picture: "https://gold-n-blog.fr/wp-content/uploads/2017/12/profile_picture_by_ivyrose96-d6hzhjx.jpg")
temeraire = RoleModel.create(first_name:"Temeraire", last_name: "Lung Tien Xiang", gender:"Male", sector:"Fictional", description: "Temeraire is fictional character in Naomi Novik's series of fantasy books. He is Dragon from China, very intelligent, has a open mind and is very critical about the humansociety he observes.", picture: "https://journalwomenwriters.files.wordpress.com/2015/02/temeraire.jpg")
terry = RoleModel.create(first_name:"Terry", last_name: "Pratchett", gender:"Male", sector:"Writing", description: "Sir Terence David John Pratchett OBE (28 April 1948 – 12 March 2015) was an English author of fantasy novels, especially comical works. He is best known for his Discworld series of 41 novels.", picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/10.12.12TerryPratchettByLuigiNovi1.jpg/220px-10.12.12TerryPratchettByLuigiNovi1.jpg")
hayao = RoleModel.create(first_name:"Hayao", last_name: "Miyazaki", gender:"Male", sector:"Film Directing,Production,Animation", description: "Hayao Miyazaki (宮崎 駿 Miyazaki Hayao, born January 5, 1941) is a Japanese animator, filmmaker, screenwriter, author, and manga artist. A co-founder of Studio Ghibli, a film and animation studio, he has attained international acclaim as a masterful storyteller and as a maker of anime feature films, and is widely regarded as one of the greatest animation filmmakers.", picture: "https://www.kanpai.fr/sites/default/files/uploads/2014/01/hayao-miyazaki-venise.jpg")
baloo = RoleModel.create(first_name:"Baloo", last_name: "of the Jungle Book", gender:"Male", sector:"Fictional", description: "Baloo (from Hindi: भालू bhālū 'bear') is a main fictional character featured in Rudyard Kipling's The Jungle Book from 1894 and The Second Jungle Book from 1895. Baloo, a sloth bear, is the strict teacher of the cubs of the Seeonee wolf pack. His most challenging pupil is the 'man-cub' Mowgli. Baloo and Bagheera, a panther, save Mowgli from Shere Khan the tiger and endeavor to teach Mowgli the Law of the Jungle in many of The Jungle Book stories.", picture: "https://vignette.wikia.nocookie.net/poohadventures/images/2/2a/Clipjungle4new.gif/revision/latest/scale-to-width-down/346?cb=20110223010150")
sherlock = RoleModel.create(first_name:"Sherlock", last_name: "Holmes", gender:"Male", sector:"Fictional", description: "Sherlock Holmes is a fictional private detective created by British author Sir Arthur Conan Doyle. Referring to himself as a 'consulting detective' in the stories, Holmes is known for his proficiency with observation, forensic science, and logical reasoning that borders on the fantastic, which he employs when investigating cases for a wide variety of clients, including Scotland Yard.", picture: "https://www.fanactu.com/medias/sherlock-holmes-la-serie-animee-de-hayao-miyazaki-va-avoir-droit-a-son-edition-blu-ray-collector_9582/sherlock-holmes-la-serie-animee-de-hayao-miyazaki-va-avoir-droit-a-son-edition-blu-ray-collector-desktop-151104.jpg")
po = RoleModel.create(first_name:"Po", last_name: "Ping Xiao", gender:"Male", sector:"Fictional", description: "Master Ping Xiao Po (birth name: Li Lotus) is the title character and the protagonist of the Kung Fu Panda franchise. He is a young anthropomorphic giant panda in his 20s, who is improbably chosen as the Dragon Warrior, champion of the Valley of Peace in the first film. He is the adoptive son of Mr. Ping, and is one of Master Shifu's students. Po is also the prophesied Dragon Warrior, as well as the warrior of black and white. In Kung Fu Panda: Legends of Awesomeness, Po is revealed to have the ability to be able to learn kung fu at a glance.
Po is also the team leader of the Furious Five, although he is not properly part of as he is considered as a second master after Shifu to the Furious Five.
The character has received largely positive critical reception, reaching influence to serve as the other characters, video games and films in the media.", picture: "https://vignette.wikia.nocookie.net/vsbattles/images/b/bf/Kung-Fu-Panda-Render-copy.gif/revision/latest?cb=20151231071437")
frederic = RoleModel.create(first_name:"Frederic", last_name: "Back", gender:"Male", sector:"Film Directing,Artist", description: "Frédéric Back (April 8, 1924 – December 24, 2013) was a Canadian artist and film director of short animated films. During a long career with Radio-Canada, the French-language service of the Canadian Broadcasting Corporation, he was nominated for four Academy Awards, winning two, for his 1981 film Crac and the 1987 film The Man Who Planted Trees.", picture: "https://maisonsaine.ca/wp-content/uploads/2014/03/frederic-back.jpg")
sixto = RoleModel.create(first_name:"Sixto", last_name: "Rodriguez", gender:"Male", sector:"Music", description: "Sixto Diaz Rodriguez, known professionally as Rodriguez (born July 10, 1942), is an American singer-songwriter from Detroit, Michigan. His career initially proved short lived in the United States, but unknown to Rodriguez his albums became extremely successful and influential in South Africa, where he is believed to have sold more records than Elvis Presley. Because of scarce information about Rodriguez, it was incorrectly rumored there that he had committed suicide shortly after releasing his first album.
In the 1990s, determined South African fans managed to find and contact Rodriguez, which led to an unexpected revival of his musical career. This was told in the 2012 Academy Award–winning documentary film Searching for Sugar Man and helped give Rodriguez a measure of fame in his home country. In May 2013, Rodriguez received an honorary Doctor of Humane Letters degree from his alma mater, Wayne State University, in Detroit.
Rodriguez has been living in Detroit's historic Woodbridge neighborhood, through which he is seen walking in Searching for Sugar Man. He is known to live a simple life, possessing no telephone or cell phone of his own, and occasionally visiting bars in the Cass Corridor section of Detroit near Woodbridge and Midtown Detroit, such as the Old Miami pub, where he has performed live concerts for small local crowds.", picture: "https://static.lexpress.fr/medias_2355/w_480,h_270,c_fill,g_north/v1376294574/sugar-man_1206231.jpg")
audrey = RoleModel.create(first_name:"Audrey", last_name: "Hepburn", gender:"Female", sector:"Acting", description: "Audrey Hepburn (born Audrey Kathleen Ruston; 4 May 1929 – 20 January 1993) was a British actress and humanitarian. Recognised as a film and fashion icon, Hepburn was active during Hollywood's Golden Age. She was ranked by the American Film Institute as the third-greatest female screen legend in Golden Age Hollywood, and was inducted into the International Best Dressed List Hall of Fame.
Born in Ixelles, Brussels, Hepburn spent her childhood between Belgium, England, and the Netherlands. In Amsterdam, she studied ballet with Sonia Gaskell. She moved to London in 1948, where she continued her ballet training with Marie Rambert. She began performing as a chorus girl in West End musical theatre productions. Following minor appearances in several films, Hepburn starred in the 1951 Broadway play Gigi after being spotted by French novelist Colette, on whose work the play was based.", picture: "https://img.lemde.fr/2018/12/28/1760/0/5883/5883/688/0/60/0/7fc1565_VK-wgq43wlMVtOYleB4NuSId.jpg")
john = RoleModel.create(first_name:"John", last_name:"Doe", gender:"Other", sector:"Tech", description:"‘John Doe’(for males) and  'Jane Doe' (for females)  were fictitious names used by eighteenth century lawyers so as to allow the real plaintiff to use the efficient procedure known as ejectment to establish title to land instead of the more cumbrous procedure known as the writ of right. Such cases were reported in such manner as, Doe, d. (ie on the demise of) Smith v Jones.", picture:"https://completeconcussions.com/drive/uploads/2017/10/detail-john-doe.jpg")
michelle = RoleModel.create(first_name: "Michelle", last_name: "Obama", gender: "Female", sector: "Law,Writing,Politics", description: "Michelle LaVaughn Obama is an American lawyer, university administrator and writer, who was First Lady of the United States from 2009 to 2017. She is married to the 44th U.S. president, Barack Obama, and was the first African-American first lady.", picture:"https://www.ticketnews.com/wp-content/uploads/michelle-obama-large.jpg")
eli = RoleModel.create(first_name: "Elizabeth", last_name: "Nyamayoro", gender: "Female", sector: "Politics", description: "She is a political scientist and senior advisor to Under-Secretary-General and Executive Director for UN Women. Nyamayaro is also the head of HeForShe, a movement founded by UN Women to empower all humans, especially men and boys, to have a voice and take action to achieve gender equality in their own lifetime.", picture:"https://ravishly-9ac9.kxcdn.com/sites/default/files/styles/article/public/field/image/elizabeth.jpeg?itok=FNTFEHjN")
simone = RoleModel.create(first_name: "Simone", last_name: "Veil", gender: "Female", sector: "Politics,Law", description: "Simone Veil was a French lawyer and politician who served as Minister of Health under Valéry Giscard d'Estaing, President of the European Parliament and member of the Constitutional Council of France.

A survivor of the Auschwitz-Birkenau concentration camp where she lost part of her family during the Holocaust; she served as the first president of the Fondation pour la Mémoire de la Shoah, from 2000 to 2007, and subsequently as honorary president. She was elected to the Académie française in November 2008. She was best known for pushing forward the law legalizing abortion in France on 17 January 1975. She and her husband were buried in the Panthéon on July 1, 2018. Only the fifth woman in history to be accorded this burial honor, she was eulogized during the reinterment ceremony by President Emmanuel Macron.", picture:"https://resize-elle.ladmedia.fr/r/625,,forcex/crop/625,804,center-middle,forcex,ffffff/img/var/plain_site/storage/images/societe/edito/chere-simone-veil-3784228/90386399-2-fre-FR/Chere-Simone-Veil.jpg")
marie = RoleModel.create(first_name: "Marie", last_name: "Curie", gender: "Female", sector: "Physics,Chemistry", description: "Marie Skłodowska Curie was a Polish and naturalized-French physicist and chemist who conducted pioneering research on radioactivity. She was the first woman to win a Nobel Prize, the first person and only woman to win the Nobel prize twice, and the only person to win the Nobel Prize in two different scientific fields. She was part of the Curie family legacy of five Nobel Prizes. She was also the first woman to become a professor at the University of Paris, and in 1995 became the first woman to be entombed on her own merits in the Panthéon in Paris.", picture:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Marie_Curie_c1920.jpg/440px-Marie_Curie_c1920.jpg")
jk = RoleModel.create(first_name: "J. K.", last_name: "Rowling", gender: "Female", sector: "Writer", description: "She  is a British novelist, philanthropist, film producer, television producer and screenwriter, best known for writing the Harry Potter fantasy series. The books have won multiple awards, and sold more than 500 million copies, becoming the best-selling book series in history. They have also been the basis for a film series, over which Rowling had overall approval on the scripts and was a producer on the final films in the series.", picture:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/J._K._Rowling_2010.jpg/440px-J._K._Rowling_2010.jpg")
george = RoleModel.create(first_name: "George", last_name: "Sand", gender: "Male", sector: "Writer", description: "Amantine Lucile Aurore Dupin, best known by her nom de plume George Sand, was a French novelist, memoirist, and socialist. One of the most popular writers in Europe in her lifetime, being more popular than both Victor Hugo and Honore de Balzac in England in the 1830s and 1840s, Sand is recognised as one of the most notable writers of the European Romantic era.", picture:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/George_Sand.PNG/440px-George_Sand.PNG")
roya = RoleModel.create(first_name: "Roya", last_name: "Mahboob", gender: "Female", sector: "Business", description: "Roya Mahboob is a businesswoman and entrepreneur from Afghanistan. She founded and serves as CEO of the Afghan Citadel Software Company, a full-service software development company based in Herat, Afghanistan. She has received attention for being among the first IT female CEOs in Afghanistan, where it is still relatively rare for women to work outside the home", picture:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Roya_Mahboob.jpg/440px-Roya_Mahboob.jpg")
kathrine = RoleModel.create(first_name: "Kathrine", last_name: "Switzer", gender: "Female", sector: "Sports,Writer", description: "Kathrine Switzer is an American marathon runner, author, and television commentator. In 1967, she became the first woman to run the Boston Marathon as a numbered entrant. During her run, race official Jock Semple attempted to stop Switzer and grab her official bib; however, he was shoved to the ground by Switzer's boyfriend, Thomas Miller, who was running with her, and she completed the race. It was not until 1972 that women were allowed to run the Boston Marathon officially.", picture:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Kathrine_Switzer_at_the_2011_Berlin_Marathon_Expo.jpg/440px-Kathrine_Switzer_at_the_2011_Berlin_Marathon_Expo.jpg")
mary = RoleModel.create(first_name: "Mary", last_name: "Robinson", gender: "Female", sector: "Politics", description: "Mary Robinson is an Irish Independent politician who served as the seventh President of Ireland, becoming the first woman to hold this office. She also served as United Nations High Commissioner for Human Rights from 1997 to 2002 and a Senator for the University of Dublin from 1969 to 1989. She first rose to prominence as an academic, barrister and campaigner.", picture:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Mary_Robinson_%282014%29.jpg/440px-Mary_Robinson_%282014%29.jpg")
barack = RoleModel.create(first_name: "Barack", last_name: "Obama", gender: "Male", sector: "Politcs,Law", description: "Barack Obama is an American attorney and politician who served as the 44th president of the United States from 2009 to 2017. A member of the Democratic Party, he was the first African American to be elected to the presidency. He previously served as a U.S. senator from Illinois from 2005 to 2008.", picture:"https://upload.wikimedia.org/wikipedia/commons/8/8d/President_Barack_Obama.jpg")
mdbappe = RoleModel.create(first_name: "Kylian", last_name: "Mbappé", gender: "Male", sector: "Sports", description: "Kylian Mbappé is a French professional footballer who plays as a forward for Ligue 1 club Paris Saint-Germain and the France national team. Considered one of the best players in the world, he is known for his finishing, dribbling, and speed. He is considered the world's most expensive player from a transfer value perspective by the CIES.", picture: "https://media.ouest-france.fr/v1/pictures/b1406ba14ea2fe8e81ec0379b7b35201-football-kylian-mbappe-atteint-la-barre-des-100-buts-en-carriere.jpg?width=1260&height=712&focuspoint=50%2C24&cropresize=1&client_id=cmsfront&sign=a1485b76977e036484383ff18d02007635700aeb550b434a6f2b1311108efedc")

# Future Me
challenge = Challenge.create(title: "Start planning for the future", category: "Future me", description: "Where do you picture yourself in 5 years ? At university ? Studying ? Travelling ? Where ? What ? Why ? Now is the time to be ambitious ! Write it down to remember it", role_model_id: sherlock.id)
challenge8 = Challenge.create(title: "Find your Ikagai", category: "Future me", description: "Each individual's ikigai is personal to them and specific to their lives, values and beliefs. It reflects the inner self of an individual and expresses that faithfully, while simultaneously creating a mental state in which the individual feels at ease. Find your Ikagai!", role_model_id: po.id)
challenge9 = Challenge.create(title: "Do research", category: "Future me", description: "Go find about a sector that you are interested in. Is it tech ? Agriculture ? Fashion ? Entrepreneurship ? Remember to think outside of the box !", role_model_id: terry.id)
challenge10 = Challenge.create(title: "Find inspiration", category: "Future me", description: "Reach out to somebody that you admire on a personal or professional level and start a conversation", role_model_id: mascotte.id)
challenge11 = Challenge.create(title: "Time to clean up the dirt", category: "Future me", description: "Clear up your social media from anything makes you sad of insecure", role_model_id: sofia.id)
challenge20 = Challenge.create(title: "Better world", category: "Future me", description: "Think of three ideas that would make the world better. No constraint. Use your imagination !", role_model_id: temeraire.id)

# Daily activities
challenge7 = Challenge.create(title: "When was the last time you had a sense of success ?", category: "Daily activities", description: "Write down a success of yours in a dairy or on a word document with the competences you needed to make it a success", role_model_id: mascotte.id)
challenge2 = Challenge.create(title: "Go outside", category: "Daily activities", description: "Go out in the sun and take a moment to appreciate the beauty of your world. It is important to feel grateful now and then to be at peace with yourself and with others", role_model_id: aragorn.id)
challenge12 = Challenge.create(title: "I am awesome", category: "Daily activities", description: "Write down up to 5 things you like about yourself. Not so simple right ?", role_model_id: riri.id)
challenge13 = Challenge.create(title: "Favorite values", category: "Daily activities", description: "Write down up to 5 qualities you like in others", role_model_id: riri.id)
challenge14 = Challenge.create(title: "Me insecure ? Never !", category: "Daily activities", description: "Write down up to 3 insecurities on a piece of paper and get rid of it (trash, fireplace ... Make it eco-friendly 🌿) how did it feel ? Don’t be afraid to be to too dramatic", role_model_id: baloo.id)
challenge15 = Challenge.create(title: "Baby you're a firework !", category: "Daily activities", description: "Need to get relieved of tensions ? Scream now ! Feeling shy ? Scream louder !! This challenge is for you", role_model_id: audrey.id)
challenge16 = Challenge.create(title: "Be autonomous", category: "Daily activities", description: "Are you afraid of loneliness ? Do be, doing activities on your own can be very empowering ! Try it out : go for a walk, a museum, a cinema, shopping and experience autonomy and independence !", role_model_id: mascotte.id)
challenge22 = Challenge.create(title: "Passion", category: "Daily activities", description: "Do you have passion, or a dream passion ? Do you take enough time to pratice it ? Pratice for one hour today !", role_model_id: frederic.id)

# Curiosity
challenge3 = Challenge.create(title: "Discover the world", category: "Curiosity", description: "There's a great documentary for you to watch", role_model_id: elon.id)
challenge4 = Challenge.create(title: "Interested in politics?", category: "Curiosity", description: "Did you know that agriculture is the most polluting industry in the world?", role_model_id: hayao.id)
challenge17 = Challenge.create(title: "Learn from others", category: "Curiosity", description: "Go find a new role model in your inspiration section ! 😉", role_model_id: mascotte.id)
challenge21 = Challenge.create(title: "Language", category: "Curiosity", description: "If your where able to learn in one second a whole language, which ones would you learn ?", role_model_id: temeraire.id)


# Interactions
challenge5 = Challenge.create(title: "What could you do better ?", category: "Interactions", description: "Ask a friend, a family member (someone trustworthy) if they believe that you are a good friend", role_model_id: baloo.id)
challenge6 = Challenge.create(title: "Be a good friend", category: "Interactions", description: "What is a good friend ? Find some attributes good friends have according to you and impersonnate them for one entire day.", role_model_id: mascotte.id)
challenge18 = Challenge.create(title: "Support others", category: "Interactions", description: "Spot someone around you who looks sad or lonely. Start a conversation or send them a message today to ask them how they are doing.", role_model_id: sixto.id)
challenge19 = Challenge.create(title: "Make friends", category: "Interactions", description: "Talk to somebody that you seed everybody but to whom you harldy ever talk to or have never talked to. Introduce yourself and start a conversation ! Never miss an opportunity to make friends. And remember, networking is key for a prosperous careers!", role_model_id: mascotte.id)

Participation.create(user_id: user.id, challenge_id: challenge.id, feedback: "I loved it", appreciation: 5, difficulty: 2)
Participation.create(user_id: user.id, challenge_id: challenge2.id, feedback: "It sucked", appreciation: 1, difficulty: 4)
Participation.create(user_id: user2.id, challenge_id: challenge.id, feedback: "Cool, i want more !", appreciation: 4, difficulty: 3)
Participation.create(user_id: user2.id, challenge_id: challenge2.id, feedback: "I thought it was amusing", appreciation: 3, difficulty: 1)

Participation.create(user_id: user4.id, challenge_id: challenge.id, feedback: "I loved it", appreciation: 5, difficulty: 2)
Participation.create(user_id: user4.id, challenge_id: challenge2.id, feedback: "It sucked", appreciation: 1, difficulty: 4)
Participation.create(user_id: user4.id, challenge_id: challenge3.id, feedback: "Cool, I want more !", appreciation: 4, difficulty: 3)
Participation.create(user_id: user4.id, challenge_id: challenge6.id, feedback: "I thought it was amusing", appreciation: 3, difficulty: 1)
Participation.create(user_id: user4.id, challenge_id: challenge8.id, feedback: "I really enjoyed it", appreciation: 3, difficulty: 1)
Participation.create(user_id: user4.id, challenge_id: challenge7.id)


puts "End"
